//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarShip.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Flight_Passanger = new HashSet<Flight_Passanger>();
        }
    
        public int id { get; set; }
        public Nullable<int> SpaceshipId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Passanger> Flight_Passanger { get; set; }
        public virtual Route Route { get; set; }
        public virtual Spaceship Spaceship { get; set; }
    }
}
