//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarShip.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpaceShipDB : DbContext
    {
        public SpaceShipDB()
            : base("name=SpaceShipDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Flight_Passanger> Flight_Passanger { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<Planet> Planet { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<Spaceship> Spaceship { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trouble> Trouble { get; set; }
        public virtual DbSet<Trouble_Passanger> Trouble_Passanger { get; set; }
        public virtual DbSet<Trouble_Planet> Trouble_Planet { get; set; }
    }
}
