//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarShip.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trouble_Planet
    {
        public int id { get; set; }
        public Nullable<int> Trouble_Id { get; set; }
        public Nullable<int> Planet_Id { get; set; }
    
        public virtual Planet Planet { get; set; }
        public virtual Trouble Trouble { get; set; }
    }
}
